name: mytodoapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8
  google_fonts: ^6.2.1
  intl: ^0.19.0
  random_string: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
